export enum JobRole {
  Developer = 'Developer',
  Analyst = 'Analyst',
  DataScientist = 'Data Scientist',
  UXDesigner = 'UX Designer',
  ProjectManager = 'Project Manager',
  QualityAssurance = 'Quality Assurance',
  SalesExecutive = 'Sales Executive',
  MarketingSpecialist = 'Marketing Specialist',
  NetworkEngineer = 'Network Engineer',
  SystemAdministrator = 'System Administrator',
  Accountant = 'Accountant',
  HumanResourcesManager = 'Human Resources Manager',
  OperationsManager = 'Operations Manager',
  CustomerServiceRepresentative = 'Customer Service Representative',
  ResearchAssistant = 'Research Assistant',
  GraphicDesigner = 'Graphic Designer',
  ContentWriter = 'Content Writer',
  SoftwareArchitect = 'Software Architect',
  ProductOwner = 'Product Owner',
  CEO = 'CEO',
  Custodian = 'Custodian',
}
